### ISSUE TITLE
What is the in-context prompt to use for GPT for open-ended T2I evaluation?

### ISSUE THREAD

**Issue by linzhiqiu** [aszala/VPEval#1]

**Comment by aszala** [comment]
We just upload added the script for program generation.

Please see the prompt + in-context examples at the top of this [file](https://github.com/aszala/VPEval/blob/53a3b0ce46a8b00602e39ed364a101a20b7ae3d5/src/open_ended_prompt_generation/generate_open_ended_prompts.py#L9).

**Comment by linzhiqiu** [comment]
I think there is a type for "openai_completion()" function. Here is the corrected version:

```
def openai_completion(prompt):
    resp = openai.ChatCompletion.create(
            model='gpt-3.5-turbo',
            messages=[{"role": "user", "content": prompt}],
            temperature=0
        )

    return resp['choices'][0]['message']['content']
```


Also, in the prompt you ask GPT to output "one or two programs". However, I am not seeing where you detect whether the output is 1 or 2 programs.

**Comment by aszala** [comment]
We have updated the GPT engine to change depending on using [Azure](https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart?tabs=command-line&pivots=programming-language-studio) or not (default does not use Azure).

See updated code [file](https://github.com/aszala/VPEval/blob/0eabdc83268f4a47b08ee53bc97fe261c56ef7b7/src/open_ended_prompt_generation/generate_open_ended_prompts.py#L331).
