### ISSUE TITLE
VPEval inference code

### ISSUE THREAD

**Issue by BrianG13** [aszala/VPEval#3]
Hi guys, 
Thanks for releasing the code of your work! Very cool and interesting!

I was just wondering, if there is an option for inference code that we can load an image+prompt and receive the open-ended (or skill) evaluation results.
As I understand, this method use ChatGPT for visual programming, that means that I will need to query ChatGPT online during this process. Right?

Thanks!

**Comment by aszala** [comment]
Hi,

Thanks for your interest in our work!
We have released an inference notebook you can use for your own images/prompts.
See it [here](https://github.com/aszala/VPEval/blob/main/inference.ipynb).

Yes, we use ChatGPT, you do not need to use the online interface. Instead, you can provide your OpenAI API key in the notebook and then use the Python API to generate the programs.
