### ISSUE TITLE
Inference.ipynb: Different Objective Detection Results Depending on CPU/CUDA

### ISSUE THREAD

**Issue by JooYoungYoo** [aszala/VPEval#4]
Hi! :D
Thank you for suggesting interesting work and uploading the inference code!

By the way, I am having trouble running inference.ipynb.
It works well when I set the device as CPU.
However, when I set the device as a specific CUDA number (e.g. cuda:3), it doesn't return any objective detection results.
I have also tried setting different thresholds for the box and text (box_threshold. text_threshold), but I can't.

Could you please check the inference.ipynb with the specific CUDA number?

**Comment by aszala** [comment]
Hi,
Thanks for your interest in our work!

Have you tried the notebook in Colab? It should work on CUDA there.

Also to clarify is your issue when you try "cuda" in general or just when you have a specific number like "cuda:3"?
If it works with just "cuda" and not "cuda:3" you can instead just set the environment variable `CUDA_VISIBLE_DEVICES`, e.g., `export CUDA_VISIBLE_DEVICES=3` and set devices to just "cuda". This will use GPU 3.
